### ISSUE TITLE
Nothing show on the display.

### ISSUE THREAD

**Issue by Sesshu620** [clio-one/cardano-on-the-rocks#3]
![Image from iOS (1)](https://user-images.githubusercontent.com/46942779/69236354-6fd80380-0be7-11ea-998f-ad5aa875712e.jpg)
![Image from iOS (2)](https://user-images.githubusercontent.com/46942779/69236356-6fd80380-0be7-11ea-8e15-4b4346ba5b01.jpg)
![Image from iOS](https://user-images.githubusercontent.com/46942779/69236357-70709a00-0be7-11ea-8dff-26395c07e078.jpg)

Does anyone has any idea where should I check ? Thanks

**Comment by gufmar** [comment]
can you please provide the logfile from `/var/log/cardano-on-the-rocks_initial-setup.log` ?

We have some reports that connection attempts to github.com/clio-one/cardano-luma and /luma.oled time out. (This are the OLED drivers)

If this is the case we are currently testing a new image release already containing these drivers. 

In general, we want to provide a minimal and as little as possible different image from standard Armbian. What happens during the first installation and possible updates should be published transparently and comprehensibly via github.

**Comment by MajorLazer2142** [comment]
Hey,

I have the same issue (problem) as Sesshu620. I had flash yesterday the Cardano-on-the-Rocks edition of the Armbian Linux on the eMMC Module. If I start the rock pi the LED hat flash red. After connection with the LAN-Cable it turns blue for 2 or 3 seconds and then directly green. But the OLED is still black..... . Futhermore then I disconnect the LAN-Cable the LED is still green.
I double check all connections and the polarity but it seems all okay. What's wrong there. Any idea ?
Thanks !

**Comment by from-ufa** [comment]
Hello everybody! I have the same problem! The light panel does not light!

**Comment by Bombsquadted2** [comment]
Yep, same here.  The flash went seamless and  I've got Ubuntu Bionic with Armbian Linux successfully installed and fully updated/upgraded yet...  nooooo light.

FWIW, I'm running the AllNet Cardano on the rocks advanced kit with the PI-4b

**Comment by from-ufa** [comment]
Hello @gufmar this is my log file
![Снимок экрана 2019-12-25 в 07 37 27](https://user-images.githubusercontent.com/40315165/71429699-c86c5600-26e9-11ea-8911-2e4a7dcaac0d.png)
 at once, then setup is running - logo cardano is flashing, but then device rebooting - i have a black screen

**Comment by from-ufa** [comment]
![photo_2019-12-25 11 32 41](https://user-images.githubusercontent.com/40315165/71435303-4dfffe00-270a-11ea-8783-8c63f0d8f2fb.jpeg)

display not work

**Comment by gufmar** [comment]
Hello all, 
We received some reports, about invalid packages or downloads timing out. 
Our goal was to keep the image small and update the initial setup script over time as required. 

We now have an image including more packages, and so the display should turn on out of the box.
please us this link meanwhile to download the image
https://edu.clio.one/wp-content/uploads/2019/11/191126b.zip

**Comment by MajorLazer2142** [comment]
Thank you ! The display works now perfectly 👍

**Comment by kwai-chang** [comment]
Maybe that helps for finding a solution, because getting some errors by running ./initial-setup.sh

Hit:4 https://apt.armbian.com bionic InRelease
Reading package lists... Done
./initial-setup.sh: line 58: 191120: No such file or directory
install OLED library
sudo: python3: command not found
blue and green LED off
./initial-setup.sh: line 77: echo: write error: Device or resource busy
./initial-setup.sh: line 82: echo: write error: Device or resource busy
Show Cardano Logo on Display
sudo: python3: command not found
green LED on
./initial-setup.sh: line 93: echo: write error: Device or resource busy
./initial-setup.sh: line 99: 191120: No such file or directory
