### ISSUE TITLE
On the rocks startup

### ISSUE THREAD

**Issue by rbacquie** [clio-one/cardano-on-the-rocks#6]
Order this unit and using the preferred flash file and I am not getting the screen to do ad instructed on the guide and when connecting a screen a get a rockpi login: prompt after going the the color sequence from green  to blue to green and the its stuck

**Comment by gufmar** [comment]
can you login with the image default login credentials 
user: root
pass: 1234

**Comment by rbacquie** [comment]
tried that last night got in now trying to do the setup but the screen is still not working

**Comment by gufmar** [comment]
just to verify what you mean by "preferred flash file" 
Did you download and flash the images from the guideline at 
https://edu.clio.one/lessons/cardano-on-the-rocks/lessons/linux-image-flashing/

If yes, can you please login and look at the initial-setup logfile (for LED and Display) 
You can find it at `/var/log/cardano-on-the-rocks_initial-setup.log`

**Comment by rbacquie** [comment]
Yes did that exactly, reflashed the eMMC twice then I install a hd monitor and saw it was requesting a login which you provided and worked fine however Display is still not functioning

**Comment by gufmar** [comment]
can you please post the content of the setup logfile at `/var/log/cardano-on-the-rocks_initial-setup.log` ?

**Comment by rbacquie** [comment]
@gufmar  I manually flashed the initial setup file and all is fine now, is there a better guide to settings up a cardano node on this unit since the current guide was not set up for the ITN

**Comment by gufmar** [comment]
so the OLED display is working now? 
There is a new setup guide for a current 0.8.15 version of Jormungandr
https://medium.com/@carloslopezdelara/how-to-set-up-a-stake-pool-in-cardano-itn-incentivized-test-net-jormungandr-0-8-14-5e5ebf24dfde

at step 3.3 (download the binary) you need to pick the aarch64-unknown-linux-gnu file.

**Comment by rbacquie** [comment]
@gufmar yes the display is now working maybe during the initial install it crashed not sure but after using the bash cmd to execute the setup script its fine, question I followed the guide to the end download the latest jormungandr where should start with this setup? and to download a file I use the wget cmd?

**Comment by gufmar** [comment]
I prepared a little script at https://github.com/clio-one/cardano-on-the-rocks/tree/master/scripts/Jormungandr
The readme describes how to use it, to download the latest binary, create wallets, register a pool on chain ecc.

Then I recommend using the previously mentioned medium guideline, or also official ones published at https://iohk.zendesk.com/hc/en-us/articles/360039342934-How-to-install-Jormungandr-Networking-Linux-

I also recommend to get familiar with the linux command line and tools like wget, as it is very useful for Pool operations then.
Alternatively you can enable a GUI desktop on your RockPi with armbian-config (might watch this video on how to do: https://youtu.be/Gr9m9av3ZaE?t=95) 

After the technical setup you need to register your pool at https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry

**Comment by rbacquie** [comment]
i followed those instructions and the address generated was no good
