### ISSUE TITLE
Cardano Rock Pi and Haskell 

### ISSUE THREAD

**Issue by rbacquie** [clio-one/cardano-on-the-rocks#7]
I would if possible like to get confirmation that this rock pi 4b will be compatible with cardano shelly haskell testnet/mainnet once it has launched which will be very soon.

I was informed there maybe issues with the RK 3339

**Comment by rbacquie** [comment]
I take it that it's TRUE since I'm being ignored

**Comment by gufmar** [comment]
Hi @rbacquie 
We can't tell for now. We know two Haskell developers have private nodes running on their Raspberry Pi4.
But they fully focus to deliver Test- and Mainnet now and plan to extend plattform compatibility only later...

**Comment by rbacquie** [comment]
What about the theory that the pi can not handle the transaction load?

Also can we have access to starting a Haskell node for pure testing as well
with the pi 4b
